# Site settings
title: "The Codex d'Annwn"
author: "Argent"
description:
  "A searchable D&D 5e homebrew spell list, sorted by class and level."
baseurl: "/Codex-d-Annwn" # the subpath of your site, e.g. /blog/
url: "https://argentdragonsclaw.github.io" # the base hostname & protocol for your site
source-url: "https://github.com/ArgentDragonsClaw/Codex-d-Annwn/"
permalink: "/:categories/:title"
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']

# Build settings
markdown: kramdown
highlighter: pygments

# Site defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      category: "spells"
